### ISSUE TITLE
Isn't it O(n^2)?

### ISSUE THREAD

**Issue by elgs** [mattn/i_cant_believe_it_can#1]
I just had a quick look at the code. I might be wrong, but isn't it O(n^2)?

**Comment by mattn** [comment]
This is a code provided in this paper: https://arxiv.org/abs/2110.01111

![image](https://user-images.githubusercontent.com/10111/136595799-afd78ce3-521e-4379-8bd2-9ceacc55458d.png)

**Comment by elgs** [comment]
Yeah, I read that paper following the link you provided. I am just curious if this is a serious paper or just for fun. This looks like an O(n^2), but I might be wrong, because I am not good at algorithms.

**Comment by mattn** [comment]
Yes, As you know this is O(n^2).

**Comment by elgs** [comment]
Thanks. So is there any practical use for this sorting algorithm? Other than dead simple to implement?

**Comment by mattn** [comment]
No~! This is Joke repository! 😄

**Comment by elgs** [comment]
Got it thanks! But it's fun to read such a dead simple sort algorithm.
